[phases.setup]
nixPkgs = ["python311", "bash"]

[phases.build]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "python start_arbitrage.py"

[variables]
PYTHON_VERSION = "3.11"
